name: "Tepco 東京電力"
description: "Unofficial add-on for Tepco (東京電力) power monitoring service."
version: "4.0.3"
slug: "Tepco"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  username: ""
  password: ""
  long_live_token: ""
schema:
  username: str
  password: password
  long_live_token: str
ports:
  8444/tcp: 8444