name: "Tepco 東京電力"
description: "Unofficial add-on for Tepco (東京電力) power monitoring service."
version: "4.0.9"
slug: "tepco"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  username: ""
  password: ""
schema:
  username: str
  password: password