# .github/workflows/release.yml
name: Go Release Build

on:
  push:
    tags:
      - "v*"   # 只在打 tag 时触发，例如 v1.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, arm]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build for Linux ${{ matrix.arch }}
        run: |
          mkdir -p build
          case "${{ matrix.arch }}" in
            amd64)
              GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/enecle-linux-amd64 .
              ;;
            arm64)
              GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o build/enecle-linux-aarch64 .
              ;;
            arm)
              GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o build/enecle-linux-arm .
              ;;
          esac
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
